- name: Unlink user settings from .zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: "^source .HOME\/.user_settings$"
    state: absent
    
- name: Link user settings to .zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: "source $HOME/.user_settings"
    insertafter: EOF

- name: Install starship
  ansible.builtin.shell: >
    wget https://starship.rs/install.sh -O install.sh && sh install.sh -y && rm install.sh
  become: true

- name: Unlink starship from .zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: 'eval "$(starship init zsh)"'
    state: absent
    
- name: Link starship to .zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'eval "$(starship init zsh)"'
    insertafter: EOF

- name: Create user settings
  template:
    src: "{{ item }}.j2"
    dest: "{{ home }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - .user_settings

- name: "Create directory for starship files"
  file:
    path: "{{ home }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

- name: Create starship settings
  template:
    src: "{{ item }}.j2"
    dest: "{{ home }}/.config/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - starship.toml

- name: "Create directory for starship files"
  file:
    path: "{{ home }}/.vscode-server/data/Machine"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
  become: true

- name: Create machine settings
  template:
    src: "{{ item }}.j2"
    dest: "{{ home }}/.vscode-server/data/Machine/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664
  with_items:
    - settings.json

- name: Install unzip
  package:
    name: unzip
    state: present
  become: true

- name: Install Fira Code Nerdfont
  shell: >
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip -O FiraCode.zip && unzip FiraCode.zip -d FiraCode && mv FiraCode/*.ttf /usr/share/fonts/ && rm -rf FiraCode FiraCode.zip
  become: true


# - name: Change ownership of directories
#   file:
#     state: directory
#     recurse: yes
#     path: "/{{ home }}/{{ item }}"
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: 0755
#   with_items: "{{ dirs }}"
#   become: true