---
roles:
  - name: professormanhattan.bravebrowser
  - name: fubarhouse.golang
  - name: professormanhattan.ruby
  - name: vaulttec.zsh
collections:
  - name: google.cloud
  - name: community.docker
  - name: community.general
  - name: community.crypto
  - name: community.general.pipx
  - name: ansible.posix
