- name: Install vnc
  include_role:
    name: vnc
  when: software|select("equalto", "vnc")

- name: Install brave
  include_role:
    name: brave
  when: software|select("equalto", "brave")

- name: Install vscode
  include_role:
    name: vscode
  when: software|select("equalto", "vscode")

- name: Install sublime
  include_role:
    name: sublime
  when: software|select("equalto", "sublime")