- name: Clone Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home }}/.tmux/plugins/tpm"

- name: Create dotfiles
  vars:
    dotfiles:
      - { dir: "{{ home }}", name: ".tmux.conf" }
      - { dir: "{{ home }}/.config/alacritty", name: "alacritty.yml" }
  block:
    - name: Create dotfiles directory
      file:
        path: "{{ item.dir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0775
      with_items: "{{ dotfiles }}"
      become: true
    - name: Create dotfiles
      template:
        src: "{{ item.name }}.j2"
        dest: "{{ item.dir }}/{{ item.name }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0775
      with_items: "{{ dotfiles }}"
      become: true
