- name: "Create dotfiles"
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.dir }}/{{ item.name }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - { dir: "{{ home }}", name: ".tmux.conf" }
    - { dir: "{{ home }}/.config/alacritty", name: "alacritty.yml" }
  become: true