- name: Install cifs
  package:
    name: cifs-utils
    state: present
  become: true

- name: Create samba credentials file
  template:
    src: "{{ item }}.j2"
    dest: "{{ home }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - .share_creds

- name: Create mountpoints
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ shares }}"
  become: true

- name: Mount network share
  ansible.posix.mount:
    src: "{{ item.uri }}"
    path: "{{ item.mountpoint }}"
    fstype: cifs
    opts: "cred={{ home }}/.share_creds,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"
    state: mounted
  with_items: "{{ shares }}"
  become: true