- name: Check if there's authorized_keys
  stat:
    path: "{{ home }}/.ssh/authorized_keys"
  register: authorized_keys
  changed_when: (not authorized_keys.stat.exists) or (authorized_keys.stat.size == 0)

- name: Install cryptography
  pip:
    name: cryptography
    state: latest
  become: true

- name: Create the SSH directory
  file:
    path: "{{ home }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Generate and install a public key pair
  when: (not authorized_keys.stat.exists or authorized_keys.stat.size == 0) and not (ssh_public_key is defined)
  block:
    - name: Generate an SSH key pair
      openssh_keypair:
        path: /tmp/id_ssh_ed25519
        type: ed25519
        passphrase: "{{ user_password }}"

    - name: Install the public key
      copy:
        src: /tmp/id_ssh_ed25519.pub
        dest: "{{ home }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600

- name: Install the existing public key
  when: ssh_public_key is defined
  authorized_key:
    user: "{{ username }}"
    key: "{{ ssh_public_key }}"

- name: Update SSH configuration to be more secure
  register: ssh_config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?Port"
      line: "Port {{ ssh_port }}"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"
  become: true

- name: Notify user about changes
  when: ((ssh_config.changed or authorized_keys.changed) and notifications)
  import_tasks: notify_user.yml
