- name: Run basic roles
  roles:
      - role: vaulttec.zsh
        when: software|select("equalto", "zsh")

      - role: system

      - role: ssh
        when: software|select("equalto", "ssh")
      
      - role: docker
        when: software|select("equalto", "docker")
      
      - role: samba
        when: software|select("equalto", "samba")