- name: Install zsh
  include_role:
    name: vaulttec.zsh
  when: software|select("equalto", "zsh")

- name: Install system
  include_role:
    name: system

- name: Install ssh
  include_role:
    name: ssh
  when: software|select("equalto", "ssh")

- name: Install docker
  include_role:
    name: docker
  when: software|select("equalto", "docker")

- name: Install samba
  include_role:
    name: samba
  when: software|select("equalto", "samba")