software:
  - zsh
  - docker
  - ssh
#  - vnc
  - samba
  - brave
  - vscode
  - sublime
  - ngrok
  - go
  - rust
  - ghidra
  - gdb
#  - qemu

apt_software:
  - terminator
  - jadx
  - apktool
  - gcc
  - g++
  - make
  - nodejs
  - npm
  - ruby

pipx_software:
  - pwntools
  - pwncat-cs
