software:
  - zsh
  - docker
  - ssh
  - nfs
  - dotfiles
  - brave
  - vscode
  - sublime
  - ngrok
  - ghidra
  - gdb
  - neovim
  - rust

apt_software:
  - alacritty
  - apktool
  - gcc
  - g++
  - golang
  - make
  - nodejs
  - npm
  - ruby
  - default-jdk-headless
  - gradle
  - maven
  - ripgrep
  - rlwrap
  - tmux
  - default-mysql-client
  - chromium
  - zoxide
  - fzf

pipx_software:
  - pwntools
  - pwncat-cs
  - impacket

pip_software:
  - requests
