software:
  - docker
  - ssh
  - vnc
  - samba
  - brave
  - vscode
  - sublime
  - ngrok
  - go
  - rust
  - ruby
  - ghidra
  - gdb
  - qemu

apt_software:
  - terminator
  - jadx
  - apktool
  - gcc
  - g++
  - make
  - nodejs
  - npm

pipx_software:
  - pwntools
  - pwncat-cs