software:
  - zsh
  - docker
  - ssh
  - vnc
  - nfs
  - brave
  - vscode
  - sublime
  - ngrok
  - ghidra
  - gdb

apt_software:
  - alacritty
  - jadx
  - apktool
  - gcc
  - g++
  - golang
  - rustc
  - make
  - nodejs
  - npm
  - ruby
  - default-jdk-headless
  - gradle
  - neovim
  - ripgrep
  - rlwrap
  - tmux
  - default-mysql-client
  - bloodhound
  - neo4j
  - seclists
  - chromium
  - zoxide
  - fzf

pipx_software:
  - pwntools
  - pwncat-cs

pip_software:
  - requests