software:
  - zsh
  - ssh
  - nfs
  - docker
  - adminer
  - apache
  - authelia
  - bazarr
  - cloudflare-ddns
  - guacamole
  - heimdall
  - notifiarr
  - mongo
  - mongo-express
  - ombi
  - plex
  - pmm
  - portainer
  - postgres
  - radarr
  - redis
  - redis-commander
  - requestrr
  - sablier
  - speedtest
  - shlink
  - sonarr
  - tautulli
  - torrenting
  - traefik
  - uptime
  - vaultwarden
  - watchtower
  - cadvisor
  - nodeexporter
  - speedtest
  - mongo
  - mongo-express
  - sablier
  - prometheus
  - grafana

apt_software:
  - gcc
  - g++
  - make
  - network-manager
  - locales
  - python3
  - pip
  - git
  - nano
  - vim
  - qemu-guest-agent
