- name: Create .env file
  template:
    src: .env.j2
    dest: "{{ docker_dir }}/.env"
    mode: 0600
  become: true

- name: Install postgres
  include_role:
    name: postgres
  when: software|select("equalto", "postgres")

- name: Install redis
  include_role:
    name: redis
  when: software|select("equalto", "redis")

- name: Install authelia
  include_role:
    name: authelia
  when: software|select("equalto", "authelia")

- name: Install traefik
  include_role:
    name: traefik
  when: software|select("equalto", "traefik")

- name: Install adminer
  include_role:
    name: adminer
  when: software|select("equalto", "adminer")

- name: Install apache
  include_role:
    name: apache
  when: software|select("equalto", "apache")

- name: Install bazarr
  include_role:
    name: bazarr
  when: software|select("equalto", "bazarr")

- name: Install cloudflare-ddns
  include_role:
    name: cloudflare-ddns
  when: software|select("equalto", "cloudflare-ddns")

- name: Install guacamole
  include_role:
    name: guacamole
  when: software|select("equalto", "guacamole")

- name: Install heimdall
  include_role:
    name: heimdall
  when: software|select("equalto", "heimdall")

- name: Install notifiarr
  include_role:
    name: notifiarr
  when: software|select("equalto", "notifiarr")

- name: Install ombi
  include_role:
    name: ombi
  when: software|select("equalto", "ombi")

- name: Install plex
  include_role:
    name: plex
  when: software|select("equalto", "plex")

- name: Install plextrakt
  include_role:
    name: plextrakt
  when: software|select("equalto", "plextrakt")

- name: Install pmm
  include_role:
    name: pmm
  when: software|select("equalto", "pmm")

- name: Install portainer
  include_role:
    name: portainer
  when: software|select("equalto", "portainer")

- name: Install radarr
  include_role:
    name: radarr
  when: software|select("equalto", "radarr")

- name: Install redis-commander
  include_role:
    name: redis-commander
  when: software|select("equalto", "redis-commander")

- name: Install requestrr
  include_role:
    name: requestrr
  when: software|select("equalto", "requestrr")

- name: Install shlink
  include_role:
    name: shlink
  when: software|select("equalto", "shlink")

- name: Install sonarr
  include_role:
    name: sonarr
  when: software|select("equalto", "sonarr")

- name: Install tautulli
  include_role:
    name: tautulli
  when: software|select("equalto", "tautulli")

- name: Install torrenting
  include_role:
    name: torrenting
  when: software|select("equalto", "torrenting")

- name: Install uptime
  include_role:
    name: uptime
  when: software|select("equalto", "uptime")

- name: Install vaultwarden
  include_role:
    name: vaultwarden
  when: software|select("equalto", "vaultwarden")

- name: Install watchtower
  include_role:
    name: watchtower
  when: software|select("equalto", "watchtower")

- name: Install nodeexporter
  include_role:
    name: nodeexporter
  when: software|select("equalto", "nodeexporter")

- name: Install cadvisor
  include_role:
    name: cadvisor
  when: software|select("equalto", "cadvisor")

- name: Install prometheus
  include_role:
    name: prometheus
  when: software|select("equalto", "prometheus")

- name: Install grafana
  include_role:
    name: grafana
  when: software|select("equalto", "grafana")