- name: Install ngrok
  include_role:
    name: ngrok
  when: software|select("equalto", "ngrok")

- block:
    - name: Install go
      include_role:
        name: fubarhouse.golang
      when: software|select("equalto", "go")
  become: true

- name: Install rust
  include_role:
    name: rust
  when: software|select("equalto", "rust")

- name: Install ruby
  include_role:
    name: professormanhattan.ruby
  when: software|select("equalto", "ruby")

- name: Install ghidra
  include_role:
    name: ghidra
  when: software|select("equalto", "ghidra")

- name: Install gdb
  include_role:
    name: gdb
  when: software|select("equalto", "gdb")