- name: Install ngrok
  include_role:
    name: ngrok
  when: software|select("equalto", "ngrok")

- name: Install ghidra
  include_role:
    name: ghidra
  when: software|select("equalto", "ghidra")

- name: Install gdb
  include_role:
    name: gdb
  when: software|select("equalto", "gdb")

- name: Create dotfiles
  include_role:
    name: dotfiles
  when: software|select("equalto", "dotfiles")